import type { Expand, UUID } from "../lib/types";

/**
 * Represents a doodad with its associated properties.
 */
export interface Doodad {
  /** The unique identifier for the doodad. */
  id: UUID;
  /**
   * The name of the doodad.
   * @minLength 1 Doodad names must be at least 1 character long.
   */
  name: string;
  /** A brief description of the doodad. */
  description: string;
  /** A URL for the doodad's image. */
  image: string;
  /** The price of the doodad. */
  price: number;
}

/**
 * Represents the body of a request to create a new doodad.
 * This interface excludes the `id` property, as it is generated by the server.
 */
export interface DoodadCreateBody extends Expand<Omit<Doodad, "id">> {}

/**
 * Represents the body of a request to update an existing doodad.
 */
export interface DoodadUpdateBody extends Expand<Partial<DoodadCreateBody>> {}
