import { Expand, UUID } from "../lib/types";

/**
 * Represents a widget with its associated properties.
 */
export interface Widget {
  /** The unique identifier for the widget. */
  id: UUID;
  /**
   * The name of the widget.
   * @minLength 1 Widget names must be at least 1 character long.
   */
  name: string;
  /** A brief description of the widget. */
  description: string;
  /** A URL for the widget's image. */
  image: string;
}

/**
 * Represents the body of a request to create a new widget.
 * This interface excludes the `id` property, as it is generated by the server.
 */
export interface WidgetCreateBody extends Expand<Omit<Widget, "id">> {}
